version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./container:/usr/share/nginx/html/container
      - ./mfe1:/usr/share/nginx/html/mfe1
      - ./mfe2:/usr/share/nginx/html/mfe2
      - ./mfe3:/usr/share/nginx/html/mfe3
      - ./shared-lib:/usr/share/nginx/html/libs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Updated k6 configuration for ARM64
  k6:
    image: grafana/k6:latest # This image supports ARM64
    platform: linux/arm64 # Explicitly specify ARM64 platform
    volumes:
      - ./tests:/tests
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - nginx
      - influxdb

  # ARM64 compatible InfluxDB
  influxdb:
    image: influxdb:1.8
    platform: linux/arm64
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  # ARM64 compatible Grafana
  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - influxdb
